### ISSUE TITLE
Panic when open some pictures on FreeBSD

### ISSUE THREAD

**Issue by Canvis-Me** [Kl4rry/simp#44]
It is good and fast to open most pictures, but it crashes on some specific pictures (high resolution photographs). Tested the program on both Linux and Windows, no same error was found. The problem is happening on FreeBSD 14.1-RELEASE-p5 with latest ports. The wm is `sway` with pure wayland. `simp` was built with `cargo build --no-default-features --features=gtk3`. And the panic.txt outputs:

```
   0: simp::main::{{closure}}
             at ./src/main.rs:447:25
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: wgpu::backend::wgpu_core::default_error_handler
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5
   7: core::ops::function::Fn::call
             at /rustc/f54dd915b0a4345ee06fd561416ad1af08b54dbb/library/core/src/ops/function.rs:79:5
   8: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/f54dd915b0a4345ee06fd561416ad1af08b54dbb/library/alloc/src/boxed.rs:2084:9
   9: wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/backend/wgpu_core.rs:3397:17
  10: wgpu::backend::wgpu_core::ContextWgpuCore::handle_error
  11: wgpu::backend::wgpu_core::ContextWgpuCore::handle_error_nolabel
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/backend/wgpu_core.rs:308:9
  12: <wgpu::backend::wgpu_core::ContextWgpuCore as wgpu::context::Context>::queue_write_texture
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/backend/wgpu_core.rs:2272:22
  13: <T as wgpu::context::DynContext>::queue_write_texture
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/context.rs:3032:9
  14: wgpu::Queue::write_texture
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/lib.rs:5499:9
  15: simp::app::image_view::texture::Texture::from_image
             at ./src/app/image_view/texture.rs:73:9
  16: simp::app::image_view::mosaic::Mosaic::from_images
             at ./src/app/image_view/mosaic.rs:69:25
  17: simp::app::image_view::ImageView::new
             at ./src/app/image_view.rs:58:22
  18: simp::app::App::handle_output
             at ./src/app.rs:117:37
  19: simp::app::App::handle_user_event
             at ./src/app.rs:352:21
  20: simp::WindowHandler::main_loop::{{closure}}
             at ./src/main.rs:431:44
  21: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/f54dd915b0a4345ee06fd561416ad1af08b54dbb/library/core/src/ops/function.rs:294:13
  22: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/f54dd915b0a4345ee06fd561416ad1af08b54dbb/library/core/src/ops/function.rs:294:13
  23: winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::single_iteration
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/wayland/event_loop/mod.rs:323:13
  24: winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::poll_events_with_timeout
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/wayland/event_loop/mod.rs:295:9
  25: winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::pump_events
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/wayland/event_loop/mod.rs:217:13
  26: winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::run_on_demand
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/wayland/event_loop/mod.rs:181:19
  27: winit::platform_impl::linux::EventLoop<T>::run_on_demand
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/mod.rs:813:56
  28: winit::platform_impl::linux::EventLoop<T>::run
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/mod.rs:806:9
  29: winit::event_loop::EventLoop<T>::run
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/event_loop.rs:231:25
  30: simp::WindowHandler::main_loop
             at ./src/main.rs:239:17
  31: simp::main
             at ./src/main.rs:481:5
  32: core::ops::function::FnOnce::call_once
             at /rustc/f54dd915b0a4345ee06fd561416ad1af08b54dbb/library/core/src/ops/function.rs:250:5
  33: std::sys::backtrace::__rust_begin_short_backtrace
             at /rustc/f54dd915b0a4345ee06fd561416ad1af08b54dbb/library/std/src/sys/backtrace.rs:152:18

panicked at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Queue::write_texture
    Not enough memory left.
```

**Comment by Kl4rry** [comment]
How large is the image uncompressed?

**Comment by Canvis-Me** [comment]
Got two different error reports. For the above error, the image is 8736x11658 of 7.4MB.

For the other error message, the image size is 5464x8192 of 12.2MB.
And the panic.txt is:
```
   0: simp::main::{{closure}}
             at ./simp/src/main.rs:447:25
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: wgpu::backend::wgpu_core::default_error_handler
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5
   7: core::ops::function::Fn::call
             at /rustc/f54dd915b0a4345ee06fd561416ad1af08b54dbb/library/core/src/ops/function.rs:79:5
   8: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/f54dd915b0a4345ee06fd561416ad1af08b54dbb/library/alloc/src/boxed.rs:2084:9
   9: wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/backend/wgpu_core.rs:3397:17
  10: wgpu::backend::wgpu_core::ContextWgpuCore::handle_error
  11: <wgpu::backend::wgpu_core::ContextWgpuCore as wgpu::context::Context>::device_create_texture
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/backend/wgpu_core.rs:1345:13
  12: <T as wgpu::context::DynContext>::device_create_texture
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/context.rs:2357:31
  13: wgpu::Device::create_texture
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/lib.rs:3084:13
  14: simp::app::image_view::texture::Texture::from_image
             at ./simp/src/app/image_view/texture.rs:60:23
  15: simp::app::image_view::mosaic::Mosaic::from_images
             at ./simp/src/app/image_view/mosaic.rs:69:25
  16: simp::app::image_view::ImageView::new
             at ./simp/src/app/image_view.rs:58:22
  17: simp::app::App::handle_output
             at ./simp/src/app.rs:117:37
  18: simp::app::App::handle_user_event
             at ./simp/src/app.rs:352:21
  19: simp::WindowHandler::main_loop::{{closure}}
             at ./simp/src/main.rs:431:44
  20: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/f54dd915b0a4345ee06fd561416ad1af08b54dbb/library/core/src/ops/function.rs:294:13
  21: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/f54dd915b0a4345ee06fd561416ad1af08b54dbb/library/core/src/ops/function.rs:294:13
  22: winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::single_iteration
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/wayland/event_loop/mod.rs:323:13
  23: winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::poll_events_with_timeout
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/wayland/event_loop/mod.rs:295:9
  24: winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::pump_events
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/wayland/event_loop/mod.rs:217:13
  25: winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::run_on_demand
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/wayland/event_loop/mod.rs:181:19
  26: winit::platform_impl::linux::EventLoop<T>::run_on_demand
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/mod.rs:813:56
  27: winit::platform_impl::linux::EventLoop<T>::run
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/mod.rs:806:9
  28: winit::event_loop::EventLoop<T>::run
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/event_loop.rs:231:25
  29: simp::WindowHandler::main_loop
             at ./simp/src/main.rs:239:17
  30: simp::main
             at ./simp/src/main.rs:481:5
  31: core::ops::function::FnOnce::call_once
             at /rustc/f54dd915b0a4345ee06fd561416ad1af08b54dbb/library/core/src/ops/function.rs:250:5
  32: std::sys::backtrace::__rust_begin_short_backtrace
             at /rustc/f54dd915b0a4345ee06fd561416ad1af08b54dbb/library/std/src/sys/backtrace.rs:152:18

panicked at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Device::create_texture
    Dimension Y is zero
```

**Comment by Canvis-Me** [comment]
It seems to be the matter of resolution, two pure white pictures with the resolution of 8736x11658 and 5464x8192 generate the same error messages provided respectively.

However, it works well with 7258x9678 pictures.

**Comment by Kl4rry** [comment]
Could you try? d617d74e2553e35ce1cfbcc892682dd9d1cb999f It should fix the bug when the image is 8192px tall and it might fix the out of memory issue.

**Comment by Canvis-Me** [comment]
The picture of 5464x8192 works fine with the latest commit dc538b9ae60b058b1bb1d05d2748583584e1710a, but for 8736x11658 it still crashes.

<details>

<summary>panic.txt</summary>

```
   0: simp::main::{{closure}}
             at /usr/home/canvis/Downloads/simp/src/main.rs:448:25
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: wgpu::backend::wgpu_core::default_error_handler
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5
   7: core::ops::function::Fn::call
             at /rustc/f54dd915b0a4345ee06fd561416ad1af08b54dbb/library/core/src/ops/function.rs:79:5
   8: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/f54dd915b0a4345ee06fd561416ad1af08b54dbb/library/alloc/src/boxed.rs:2084:9
   9: wgpu::backend::wgpu_core::ErrorSinkRaw::handle_error
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/backend/wgpu_core.rs:3397:17
  10: wgpu::backend::wgpu_core::ContextWgpuCore::handle_error
  11: wgpu::backend::wgpu_core::ContextWgpuCore::handle_error_nolabel
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/backend/wgpu_core.rs:308:9
  12: <wgpu::backend::wgpu_core::ContextWgpuCore as wgpu::context::Context>::queue_write_texture
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/backend/wgpu_core.rs:2272:22
  13: <T as wgpu::context::DynContext>::queue_write_texture
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/context.rs:3032:9
  14: wgpu::Queue::write_texture
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/lib.rs:5499:9
  15: simp::app::image_view::texture::Texture::from_image
             at /usr/home/canvis/Downloads/simp/src/app/image_view/texture.rs:73:9
  16: simp::app::image_view::mosaic::Mosaic::from_images
             at /usr/home/canvis/Downloads/simp/src/app/image_view/mosaic.rs:69:25
  17: simp::app::image_view::ImageView::new
             at /usr/home/canvis/Downloads/simp/src/app/image_view.rs:58:22
  18: simp::app::App::handle_output
             at /usr/home/canvis/Downloads/simp/src/app.rs:118:37
  19: simp::app::App::handle_user_event
             at /usr/home/canvis/Downloads/simp/src/app.rs:353:21
  20: simp::WindowHandler::main_loop::{{closure}}
             at /usr/home/canvis/Downloads/simp/src/main.rs:432:44
  21: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/f54dd915b0a4345ee06fd561416ad1af08b54dbb/library/core/src/ops/function.rs:294:13
  22: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/f54dd915b0a4345ee06fd561416ad1af08b54dbb/library/core/src/ops/function.rs:294:13
  23: winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::single_iteration
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/wayland/event_loop/mod.rs:323:13
  24: winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::poll_events_with_timeout
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/wayland/event_loop/mod.rs:295:9
  25: winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::pump_events
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/wayland/event_loop/mod.rs:217:13
  26: winit::platform_impl::linux::wayland::event_loop::EventLoop<T>::run_on_demand
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/wayland/event_loop/mod.rs:181:19
  27: winit::platform_impl::linux::EventLoop<T>::run_on_demand
             at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/winit-0.30.5/src/platform_impl/linux/mod.rs:813:56

panicked at /home/canvis/.cargo/registry/src/mirrors.ustc.edu.cn-4affec411d11e50f/wgpu-22.1.0/src/backend/wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In Queue::write_texture
    Not enough memory left.
```

</details>

**Comment by Kl4rry** [comment]
Are you using the Vulkan or OpenGL rendering backend? (You can check in the about menu). Try the other if you can by using the `WGPU_BACKEND=vulkan` env var.

**Comment by Kl4rry** [comment]
If neither work I think its an upstream wgpu/freebsd problem.

**Comment by Canvis-Me** [comment]
Only `vulkan` backend can start simp in my case. So it's probably a upstream problem. Feel free to close the issue.

**Comment by Canvis-Me** [comment]
Found a workaround by `make deinstall` the nvidia-driver to force cpu as backend. And it's okay to open 8192px tall pics after reinstall nvidia related pkgs without the commit https://github.com/Kl4rry/simp/commit/d617d74e2553e35ce1cfbcc892682dd9d1cb999f. Maybe it can be reverted. Anyway thanks for your patience and help!

**Comment by Kl4rry** [comment]
Thank you!

**Comment by jbeich** [comment]
Maybe try applying NVIDIA-specific [wgpu workaround from Veloren package](https://github.com/freebsd/freebsd-ports/blob/7cbe21434cf9/games/veloren-weekly/files/patch-wgpu-nvidia).

**Comment by jbeich** [comment]
Nevermind, I've noticed you've reported this to wgpu upstream, so will move my comment there.
